version: '2'
services:
  api:
    image: r.patrick246.de/cfhn/mycfhn-presence-ms
    restart: always
    networks:
      - default
      - traefik_net
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_net"
      traefik.frontend.rule: "Host: presence.my.cfhn.it"
      traefik.port: "8080"
    environment:
      JAVA_OPTS: "-Dcfhn.unifi.url=https://192.168.255.2:8443 -Dcfhn.unifi.password=${UNIFI_PASSWORD} -Dspring.data.mongodb.uri=mongodb://db:27017"
    volumes:
      - /etc/timezone:/etc/timezone:ro
  db:
    image: mongo
    restart: always
    volumes:
      - presencedata:/data/db
  db-admin:
    image: mongo-express
    restart: always
    networks:
      - default
      - traefik_net
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ${ADMIN_PASSWORD}
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_net"
      traefik.frontend.rule: "Host: presenceadmin.my.cfhn.it"
      traefik.port: "8081"
networks:
  traefik_net:
    external: true
volumes:
  presencedata: